// Generated by nitro
import type { Serialize, Simplify } from "nitropack/types";
declare module "nitropack/types" {
  type Awaited<T> = T extends PromiseLike<infer U> ? Awaited<U> : T
  interface InternalApi {
    '/api/audit': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/audit.get').default>>>>
    }
    '/api/availability': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/availability.get').default>>>>
    }
    '/api/availability/summary': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/availability/summary.get').default>>>>
    }
    '/api/dashboard/summary': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/dashboard/summary.get').default>>>>
    }
    '/api/data-quality/audit': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/data-quality/audit.get').default>>>>
    }
    '/api/data-quality/issues': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/data-quality/issues.get').default>>>>
    }
    '/api/data-quality/issues/:id': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/data-quality/issues/[id].get').default>>>>
      'patch': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/data-quality/issues/[id].patch').default>>>>
    }
    '/api/dispatch/assignments': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/dispatch/assignments.get').default>>>>
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/dispatch/assignments.post').default>>>>
    }
    '/api/dispatch/assignments/:id': {
      'patch': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/dispatch/assignments/[id].patch').default>>>>
    }
    '/api/dispatch': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/dispatch/index.get').default>>>>
    }
    '/api/fleet': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/fleet.get').default>>>>
    }
    '/api/fleet/:unitId': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/fleet/[unitId].get').default>>>>
    }
    '/api/health': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/health.get').default>>>>
    }
    '/api/master-data': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/master-data.get').default>>>>
    }
    '/api/master-data/locations': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/master-data/locations.get').default>>>>
    }
    '/api/master-data/shifts': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/master-data/shifts.get').default>>>>
    }
    '/api/master-data/units': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/master-data/units.get').default>>>>
    }
    '/api/production/kpis': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/production/kpis.get').default>>>>
    }
    '/api/production/tonnage/confirm-feed': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/production/tonnage/confirm-feed.post').default>>>>
    }
    '/api/production/tonnage/manual': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/production/tonnage/manual.post').default>>>>
    }
    '/api/production/trips': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/production/trips.get').default>>>>
    }
    '/api/production/trips/:tripId': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/production/trips/[tripId].get').default>>>>
    }
    '/api/reports/analytics': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/reports/analytics.get').default>>>>
    }
    '/api/reports/audit.csv': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/reports/audit.csv.get').default>>>>
    }
    '/api/reports/audit': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/reports/audit.get').default>>>>
    }
    '/api/reports/availability.csv': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/reports/availability.csv.get').default>>>>
    }
    '/api/reports/availability': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/reports/availability.get').default>>>>
    }
    '/api/reports/data-quality': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/reports/data-quality.get').default>>>>
    }
    '/api/reports/export': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/reports/export.get').default>>>>
    }
    '/api/reports/issues.csv': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/reports/issues.csv.get').default>>>>
    }
    '/api/reports/production.csv': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/reports/production.csv.get').default>>>>
    }
    '/api/reports/production': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/reports/production.get').default>>>>
    }
    '/api/simulate/tick': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/simulate/tick.post').default>>>>
    }
    '/api/users': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/users.get').default>>>>
    }
    '/__nuxt_error': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/@nuxt/nitro-server/dist/runtime/handlers/renderer').default>>>>
    }
    '/__nuxt_island/**': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/#internal/nuxt/island-renderer').default>>>>
    }
    '/api/_nuxt_icon/:collection': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/@nuxt/icon/dist/runtime/server/api').default>>>>
    }
  }
}
export {}